apiVersion : v1             #используемая для создания объекта версия API Kubernetes
kind : Pod                  #что создаем (тип объекта)
metadata:                   #данные, позволяющие идентифицировать объект (name, UID и необязательное поле namespace)
  name: my-web              #имя 
  labels:
    env: prod
    app: main
    tier: frontend
    owner: SemchishinVladimir
spec:                       #требуемое состояние объекта
  containers:
    - name: container-apache
      image: httpd:latest
      ports:
        - containerPort: 80


