apiVersion : apps/v1
kind: Deployment
metadata: 
  name: my-web-depoyment     #как называется deploy
  labels:
    app: my-k8s-application  #не обязательно, но это хорошая практика

spec:
  selector:                  #с какими подами Deployment будет работать (искатель)
    matchLabels:              #по какому ключ-значение искать подключаемый под
      project: smvn
  template:                  #описание пода
    metadata:
      labels:                #должны быть равны тем что в selector
        project: smvn 
    spec:                    #описание контейнера
      containers:
        - name: smvn-web
          image: nginx:latest
          ports:
            - containerPort: 80
          


