---
- name: Install Apache and Upload my Web Page
  hosts: all
  become: yes
 
  vars:
   source_file: /home/controller/vm-controller-project/Portfolio-Semchishin-Vladimir-Nikolaevich/My-web-site-2page/index.html 
   destin_file: /var/www/html/
 
  tasks:
  - name: Check and Print LINUX Version
    debug: var=ansible_os_family

  - block:  #=====block for REDHAT=====

    - name: Install Apache Web Server for RedHat
      yum: name=httpd state=latest
     
    - name: Start WebServer and make it enable on boot for RedHat
      service: name=httpd state=started enabled=yes
     
    - name: Copy MyHomePage to Servers
      copy: src={{ source_file }} dest={{ destin_file  }} mode=0555
      notify:  Restart Apache for RedHat

    when: ansible_os_family == "RedHat"

  - block: #====block for DEBIAN==== 

    - name: Install Apache Web Server for Debian
      apt: name=apache2 state=latest
      
    - name: Start WebServer and make it enable on boot for Debian
      service: name=apache2 state=started enabled=yes
    
    - name: Copy MyHomePage to Servers
      copy: src={{ source_file }} dest={{ destin_file  }} mode=0555
      notify:  Restart Apache for Debian
 
    when: ansible_os_family == "Debian"


  handlers:
  - name: Restart Apache for RedHat
    service: name=httpd state=restarted

  - name: Restart Apache for Debian
    service: name=apache2 state=restarted
...

