apiVersion: apps/v1
kind: Deployment
metadata: 
  name: my-web-deployment-autoscaling
  labels:
    app: my-k8s-deployment
spec:
  selector: 
    matchLabels:
      project: xyz
  template:
    metadata:
      labels:
        project: xyz
    spec:
      containers:
        - name: xyz-web
          image: nginx:latest
          ports:
            - containerPort: 80

---
apiVersion: autoscaling/v2
kind: HorizontalPodAutoscaler
metadata:
  name: my-autoscaling 
spec:     
  scaleTargetRef:                        #Что этот ресур будет масштабировать
    apiVersion: apps/v2
    kind: Deployment
    name: my-web-deployment-autoscaling
  minReplicas: 2
  maxReplicas: 6
  metrics:
    - type: Resource
      resource:
        name: cpu
        target: 
          type: Utilization
          averageUtilization: 70
    - type: Resource
      resource:
        name: memory
        target:
          type: Utilization
          averageUtilization: 80
          

---
apiVersion: v1 
kind: Service
metadata: 
  name: my-autoscaling-pod-service
  labels: 
    env: prod
    owner: SemchishinVladimir
spec:
  type: LoadBalancer
  selector:                              #выбирает pods по этому ключу
    project: xyz
  ports:
    - name: app-listener
      protocol: TCP
      port: 80
      targetPort: 80

