apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: ingress-hosts

spec:
  rules:
  - host: main.semchishinvladimir.com.
    http:
      paths:
      - pathType: Prefix
        path: "/main"
        backend:
          service:
            name: main
            port: 
              number: 80